@extends('layout.app')

@section('title', 'Mode Share Nasional')

@section('content')
    @component('layout.partials.page-header', ['number' => '05', 'title' => 'Mode Share Nasional'])
        <ol class="breadcrumb m-0 mb-0">
            <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="#">Nasional</a></li>
            <li class="breadcrumb-item active">Mode Share Nasional</li>
        </ol>
    @endcomponent

    @push('css')
        <style>
            .content-card {
                border-radius: 12px;
                border: 1px solid rgba(0, 0, 0, 0.125);
                box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);
                background: white;
            }

            .chart-title-center {
                text-align: center;
                margin-bottom: 5px;
            }

            .chart-title-center h5 {
                font-weight: bold;
                color: #333;
                margin-bottom: 2px;
                font-size: 1.1rem;
            }

            .chart-subtitle-center {
                text-align: center;
                color: #777;
                font-size: 0.85rem;
                margin-bottom: 20px;
            }

            .custom-legend {
                display: flex;
                flex-wrap: wrap;
                justify-content: center;
                margin-top: 15px;
                padding: 0 20px;
            }

            .legend-item {
                display: flex;
                flex-direction: column;
                width: 50%;
                margin-bottom: 12px;
                font-size: 0.85rem;
            }

            .legend-header {
                display: flex;
                align-items: center;
                font-weight: bold;
                color: #444;
                margin-bottom: 2px;
            }

            .legend-dot {
                width: 10px;
                height: 10px;
                border-radius: 50%;
                margin-right: 8px;
                display: inline-block;
            }

            .legend-value {
                padding-left: 18px;
                color: #666;
            }

            .section-badge {
                display: inline-flex;
                align-items: center;
                justify-content: center;
                width: 30px;
                height: 30px;
                background-color: #007bff;
                color: white;
                border-radius: 50%;
                font-weight: bold;
                font-size: 0.9rem;
                margin-right: 1rem;
                flex-shrink: 0;
            }

            .text-navy {
                color: #2a3042 !important;
            }
        </style>
    @endpush

    <div class="row mb-4" data-aos="fade-up" data-aos-duration="600">
        <div class="col-12">
            <div class="card content-card w-100 flex-column border-0" style="box-shadow: 0 4px 15px rgba(0, 0, 0, 0.05);">
                <div class="card-header d-flex align-items-center bg-white"
                    style="padding: 1.5rem; border-bottom: 1px solid rgba(0,0,0,0.05); border-radius: 12px 12px 0 0;">
                    <span class="section-badge">01</span>
                    <h5 class="fw-bold text-navy mb-0">Mode share (pemilihan moda transportasi) berdasarkan jumlah
                        pergerakan dan jumlah orang</h5>
                </div>
                <div class="card-body bg-light" style="padding: 1.5rem; border-radius: 0 0 12px 12px;">
                    <div class="row g-3">
                        <!-- 1. Distribusi Angkutan (Pergerakan) -->
                        <div class="col-lg-6 d-flex">
                            <div class="card content-card w-100 h-100 p-4 border-0 shadow-sm">
                                <div class="chart-title-center mb-3">
                                    <h5>Distribusi Angkutan</h5>
                                </div>
                                <div id="chart-pergerakan" style="height: 350px;"></div>
                                <div class="custom-legend mt-4" id="legend-pergerakan">
                                    <!-- Legend generated by JS -->
                                </div>
                            </div>
                        </div>

                        <!-- 2. Distribusi Angkutan (Orang) -->
                        <div class="col-lg-6 d-flex">
                            <div class="card content-card w-100 h-100 p-4 border-0 shadow-sm">
                                <div class="chart-title-center mb-3">
                                    <h5>Distribusi Angkutan</h5>
                                </div>
                                <div id="chart-orang" style="height: 350px;"></div>
                                <div class="custom-legend mt-4" id="legend-orang">
                                    <!-- Legend generated by JS -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @push('scripts')
        <script src="https://code.highcharts.com/highcharts.js"></script>
        <!-- Highcharts accessibility module might be useful but sticking to core is fine -->
        <script>
            $(document).ready(function() {
                var formatNum = function(num) {
                    return num.toLocaleString('id-ID');
                };

                // The backend data
                var dataPergerakan = @json($data['pergerakan']);
                var dataOrang = @json($data['orang']);

                // Filter out zeroes if desired, though Highcharts handles them
                var validPergerakan = dataPergerakan.filter(function(d) {
                    return d.y > 0;
                });
                var validOrang = dataOrang.filter(function(d) {
                    return d.y > 0;
                });

                var commonColors = [
                    '#40B0FF', // Light Blue (Motor)
                    '#6A5ACD', // Purple (Mobil)
                    '#00C97F', // Green (Kereta Perkotaan)
                    '#FF7F50', // Orange (Udara)
                    '#8190B5', // Grey/Blue (Laut)
                    '#DA70D6', // Orchid (Bus AKDP)
                    '#48D1CC', // Turquoise (Penyeberangan)
                    '#DC143C', // Crimson (Kereta Antarkota)
                    '#F4A460', // Sandy (Bus AKAP)
                    '#AFEEEE', // Pale Turquoise (KCJB)
                    '#D3D3D3' // Light Grey (Sepeda)
                ];

                function renderChartAndLegend(containerId, legendId, seriesData) {
                    var chart = Highcharts.chart(containerId, {
                        chart: {
                            type: 'pie'
                        },
                        colors: commonColors,
                        title: {
                            text: ''
                        },
                        tooltip: {
                            formatter: function() {
                                return '<b>' + this.point.name + '</b><br/>' +
                                    formatNum(this.point.y) + ' (' + this.point.pct.toString().replace('.',
                                        ',') + '%)';
                            }
                        },
                        plotOptions: {
                            pie: {
                                innerSize: '65%',
                                allowPointSelect: true,
                                cursor: 'pointer',
                                dataLabels: {
                                    enabled: true,
                                    useHTML: true,
                                    style: {
                                        fontWeight: 'normal',
                                        fontSize: '10px'
                                    },
                                    formatter: function() {
                                        // Only show labels for slices > 1% to prevent overlap, or let Highcharts manage it.
                                        // Based on mockup, it shows name, value and percentage on new lines.
                                        if (this.point.pct < 1) return null; // hide small labels to be safe

                                        return '<div style="text-align:center;">' +
                                            '<span style="font-weight:bold; color:#333;">' + this.point
                                            .name + '</span><br/>' +
                                            '<span style="font-weight:bold; color:#000;">' + formatNum(this
                                                .point.y) + '</span><br/>' +
                                            '<span style="color:#666;">(' + this.point.pct.toString()
                                            .replace('.', ',') + '%)</span>' +
                                            '</div>';
                                    }
                                },
                                showInLegend: false
                            }
                        },
                        series: [{
                            name: 'Angkutan',
                            colorByPoint: true,
                            data: seriesData
                        }],
                        credits: {
                            enabled: false
                        }
                    });

                    // Build Custom Legend
                    // To ensure color match, we'll iterate through the chart data points
                    var legendHtml = '';
                    var points = chart.series[0].points;
                    for (var i = 0; i < points.length; i++) {
                        var p = points[i];
                        if (p.y > 0) {
                            legendHtml += '<div class="legend-item">' +
                                '<div class="legend-header">' +
                                '<span class="legend-dot" style="background-color:' + p.color + '"></span>' +
                                '<span>' + p.name + '</span>' +
                                '</div>' +
                                '<div class="legend-value">' +
                                formatNum(p.y) + ' | ' + p.pct.toString().replace('.', ',') + '%' +
                                '</div>' +
                                '</div>';
                        }
                    }
                    $('#' + legendId).html(legendHtml);
                }

                renderChartAndLegend('chart-pergerakan', 'legend-pergerakan', validPergerakan);
                renderChartAndLegend('chart-orang', 'legend-orang', validOrang);
            });
        </script>
    @endpush
@endsection
